//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Scripts/SOs/Input/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/SOs/Input/Player.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Player: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""BasicActions"",
            ""id"": ""ea44aace-e530-465b-95c9-bf5b84c3c844"",
            ""actions"": [
                {
                    ""name"": ""RotRight"",
                    ""type"": ""Button"",
                    ""id"": ""d7162fe6-c710-4425-b988-b826154c45d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotLeft"",
                    ""type"": ""Button"",
                    ""id"": ""96b9e6d9-5323-4ee8-9ee9-dcdde3c75484"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamUp"",
                    ""type"": ""Button"",
                    ""id"": ""b8520e41-9d83-4296-b427-3bbe4e5c2907"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamDown"",
                    ""type"": ""Button"",
                    ""id"": ""499b5e13-3d14-44e3-9b25-20582bd59233"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamRight"",
                    ""type"": ""Button"",
                    ""id"": ""ff3e932b-df8d-49f1-bb45-2a741655b603"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CamLeft"",
                    ""type"": ""Button"",
                    ""id"": ""2b0acae3-88bb-45fe-a34a-985013c6b4e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fd7e9442-7cd0-49aa-a2fc-e17b53b9650a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""499fa2d5-c23a-4186-b390-2a06216f74ce"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83ea3de8-afd7-456a-88e1-747458936e3f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0624c562-9640-4244-bce9-09722ac49243"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""268c0f98-11f6-4ad9-ba84-1528cb336fc7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e761d139-f38b-47f2-9080-ca6fefdcf884"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BasicActions
        m_BasicActions = asset.FindActionMap("BasicActions", throwIfNotFound: true);
        m_BasicActions_RotRight = m_BasicActions.FindAction("RotRight", throwIfNotFound: true);
        m_BasicActions_RotLeft = m_BasicActions.FindAction("RotLeft", throwIfNotFound: true);
        m_BasicActions_CamUp = m_BasicActions.FindAction("CamUp", throwIfNotFound: true);
        m_BasicActions_CamDown = m_BasicActions.FindAction("CamDown", throwIfNotFound: true);
        m_BasicActions_CamRight = m_BasicActions.FindAction("CamRight", throwIfNotFound: true);
        m_BasicActions_CamLeft = m_BasicActions.FindAction("CamLeft", throwIfNotFound: true);
    }

    ~@Player()
    {
        UnityEngine.Debug.Assert(!m_BasicActions.enabled, "This will cause a leak and performance issues, Player.BasicActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BasicActions
    private readonly InputActionMap m_BasicActions;
    private List<IBasicActionsActions> m_BasicActionsActionsCallbackInterfaces = new List<IBasicActionsActions>();
    private readonly InputAction m_BasicActions_RotRight;
    private readonly InputAction m_BasicActions_RotLeft;
    private readonly InputAction m_BasicActions_CamUp;
    private readonly InputAction m_BasicActions_CamDown;
    private readonly InputAction m_BasicActions_CamRight;
    private readonly InputAction m_BasicActions_CamLeft;
    /// <summary>
    /// Provides access to input actions defined in input action map "BasicActions".
    /// </summary>
    public struct BasicActionsActions
    {
        private @Player m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BasicActionsActions(@Player wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BasicActions/RotRight".
        /// </summary>
        public InputAction @RotRight => m_Wrapper.m_BasicActions_RotRight;
        /// <summary>
        /// Provides access to the underlying input action "BasicActions/RotLeft".
        /// </summary>
        public InputAction @RotLeft => m_Wrapper.m_BasicActions_RotLeft;
        /// <summary>
        /// Provides access to the underlying input action "BasicActions/CamUp".
        /// </summary>
        public InputAction @CamUp => m_Wrapper.m_BasicActions_CamUp;
        /// <summary>
        /// Provides access to the underlying input action "BasicActions/CamDown".
        /// </summary>
        public InputAction @CamDown => m_Wrapper.m_BasicActions_CamDown;
        /// <summary>
        /// Provides access to the underlying input action "BasicActions/CamRight".
        /// </summary>
        public InputAction @CamRight => m_Wrapper.m_BasicActions_CamRight;
        /// <summary>
        /// Provides access to the underlying input action "BasicActions/CamLeft".
        /// </summary>
        public InputAction @CamLeft => m_Wrapper.m_BasicActions_CamLeft;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BasicActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BasicActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BasicActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BasicActionsActions" />
        public void AddCallbacks(IBasicActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Add(instance);
            @RotRight.started += instance.OnRotRight;
            @RotRight.performed += instance.OnRotRight;
            @RotRight.canceled += instance.OnRotRight;
            @RotLeft.started += instance.OnRotLeft;
            @RotLeft.performed += instance.OnRotLeft;
            @RotLeft.canceled += instance.OnRotLeft;
            @CamUp.started += instance.OnCamUp;
            @CamUp.performed += instance.OnCamUp;
            @CamUp.canceled += instance.OnCamUp;
            @CamDown.started += instance.OnCamDown;
            @CamDown.performed += instance.OnCamDown;
            @CamDown.canceled += instance.OnCamDown;
            @CamRight.started += instance.OnCamRight;
            @CamRight.performed += instance.OnCamRight;
            @CamRight.canceled += instance.OnCamRight;
            @CamLeft.started += instance.OnCamLeft;
            @CamLeft.performed += instance.OnCamLeft;
            @CamLeft.canceled += instance.OnCamLeft;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BasicActionsActions" />
        private void UnregisterCallbacks(IBasicActionsActions instance)
        {
            @RotRight.started -= instance.OnRotRight;
            @RotRight.performed -= instance.OnRotRight;
            @RotRight.canceled -= instance.OnRotRight;
            @RotLeft.started -= instance.OnRotLeft;
            @RotLeft.performed -= instance.OnRotLeft;
            @RotLeft.canceled -= instance.OnRotLeft;
            @CamUp.started -= instance.OnCamUp;
            @CamUp.performed -= instance.OnCamUp;
            @CamUp.canceled -= instance.OnCamUp;
            @CamDown.started -= instance.OnCamDown;
            @CamDown.performed -= instance.OnCamDown;
            @CamDown.canceled -= instance.OnCamDown;
            @CamRight.started -= instance.OnCamRight;
            @CamRight.performed -= instance.OnCamRight;
            @CamRight.canceled -= instance.OnCamRight;
            @CamLeft.started -= instance.OnCamLeft;
            @CamLeft.performed -= instance.OnCamLeft;
            @CamLeft.canceled -= instance.OnCamLeft;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BasicActionsActions.UnregisterCallbacks(IBasicActionsActions)" />.
        /// </summary>
        /// <seealso cref="BasicActionsActions.UnregisterCallbacks(IBasicActionsActions)" />
        public void RemoveCallbacks(IBasicActionsActions instance)
        {
            if (m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BasicActionsActions.AddCallbacks(IBasicActionsActions)" />
        /// <seealso cref="BasicActionsActions.RemoveCallbacks(IBasicActionsActions)" />
        /// <seealso cref="BasicActionsActions.UnregisterCallbacks(IBasicActionsActions)" />
        public void SetCallbacks(IBasicActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_BasicActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BasicActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BasicActionsActions" /> instance referencing this action map.
    /// </summary>
    public BasicActionsActions @BasicActions => new BasicActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BasicActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BasicActionsActions.AddCallbacks(IBasicActionsActions)" />
    /// <seealso cref="BasicActionsActions.RemoveCallbacks(IBasicActionsActions)" />
    public interface IBasicActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "RotRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RotLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CamLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamLeft(InputAction.CallbackContext context);
    }
}
